FROM gcr.io/distroless/java:11-nonroot
COPY target/spring-crud-thymeleaf-demo-0.0.1-SNAPSHOT.jar spring-crud-thymeleaf-demo-0.0.1-SNAPSHOT.jar
EXPOSE 8080
CMD ["spring-crud-thymeleaf-demo-0.0.1-SNAPSHOT.jar"]

